src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstNameLastName__c</fullName>
        <formula>Last_Name__c &amp;&quot; &quot;&amp;First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FirstNameLastName</label>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Hospital_DoctorHandler.cls
/**
 * Created by BRITENET on 13.12.2018.
 */


public with sharing class Hospital_DoctorHandler {
    public static String getDoctorsInJson(List<Doctor__c> doctorsToExport) {
        JSONGenerator generator = JSON.createGenerator(true);

        generator.writeStartArray();

        for (Doctor__c doc : doctorsToExport) {
            generator.writeStartObject();

            generator.writeStringField(Schema.Doctor__c.fields.Name.getDescribe().getLabel(), notBlankField(doc.FirstNameLastName__c));
            generator.writeStringField(Schema.Doctor__c.fields.Email__c.getDescribe().getLabel(), notBlankField(doc.Email__c));
            generator.writeStringField(Schema.Doctor__c.fields.Country__c.getDescribe().getLabel(), notBlankField(doc.Country__c));

            generator.writeEndObject();
        }

        generator.writeEndArray();

        return generator.getAsString();
    }

    private static String notBlankField(String field) {
        if (String.isNotBlank(field)) {
            return field;
        } else {
            return '';
        }
    }
}