src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Hospital_DoctorWrapperForSOAP.cls
/**
 * Created by BRITENET on 02.01.2019.
 */

global class Hospital_DoctorWrapperForSOAP {

    webService String webServiceDoctorId { get; set; }
    webService String webServiceDoctorFirstName { get; set; }
    webService String webServiceDoctorLastName { get; set; }
    webService String webServiceDoctorCountry { get; set; }
    webService String webServiceDoctorCity { get; set; }

    global Hospital_DoctorWrapperForSOAP(Doctor__c doctor) {
        webServiceDoctorId = doctor.Id;
        webServiceDoctorFirstName = doctor.First_Name__c;
        webServiceDoctorLastName = doctor.Last_Name__c;
        webServiceDoctorCountry = doctor.Country__c;
        webServiceDoctorCity = doctor.City__c;
    }
}