src/objects/Doctor__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>FirstNameLastName__c</fullName>
        <formula>Last_Name__c &amp;&quot; &quot;&amp;First_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>FirstNameLastName</label>
        <type>Text</type>
    </fields>
    <label>Doctor</label>
    <nameField>
        <label>Doctor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Doctors</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Hospital_DoctorPublicSiteController.cls
/**
 * Created by BRITENET on 20.12.2018.
 */

public with sharing class Hospital_DoctorPublicSiteController {
    public List<Doctor__c> randomDoctors { get; set; }
    Integer numberOfRandomDoctors;

    public Hospital_DoctorPublicSiteController(ApexPages.StandardController controller) {
        numberOfRandomDoctors = 10;
        randomDoctors = generateRandomDoctors();
    }

    private List<Doctor__c> generateRandomDoctors() {
        Integer count = [SELECT COUNT() FROM Doctor__c];
        Integer rand = Math.floor(Math.random() * count).intValue();
        List<Doctor__c> doctors = [SELECT FirstNameLastName__c,
                Email__c,
                City__c,
                Country__c
        FROM Doctor__c
        LIMIT :numberOfRandomDoctors
        OFFSET :rand];
        return doctors;
    }
}