src/objects/Hospital__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>PostalCode__c</fullName>
        <label>PostalCode</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Hospital</label>
    <nameField>
        <label>Hospital Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Hospital_HospitalSOAP.cls
/**
 * Created by BRITENET on 22.01.2019.
 */

global class Hospital_HospitalSOAP {

    webService static Hospital_HospitalWrapperForREST upsertHospital(String hospitalId, String name, String country, String city,
            String postalCode, String street) {
        Hospital__c hospital = new Hospital__c();
        if (String.isNotBlank(hospitalId)) {
            hospital = new Hospital__c(Id = hospitalId);
        }
        if (String.isNotBlank(name)) {
            hospital.Name = name;
        }
        if (String.isNotBlank(country)) {
            hospital.Country__c = country;
        }
        if (String.isNotBlank(city)) {
            hospital.City__c = city;
        }
        if (String.isNotBlank(postalCode)) {
            hospital.PostalCode__c = postalCode;
        }
        if (String.isNotBlank(street)) {
            hospital.Street__c = street;
        }
        upsert hospital;
        return new Hospital_HospitalWrapperForREST(hospital);
    }

    webService static List<Hospital_HospitalWrapperForREST> getHospitals(String hospitalId, String name, String country, String city,
            String postalCode, String street) {
        String query = 'SELECT Id, Name, Country__c, City__c, PostalCode__c, External_Id__c, Street__c FROM Hospital__c';
        List<Hospital__c> hospitals = Database.query(query);
        List<Hospital_HospitalWrapperForREST> hospitalsWrapperForSOAP = new List<Hospital_HospitalWrapperForREST>();

        for (Hospital__c hospital : hospitals) {
            hospitalsWrapperForSOAP.add(new Hospital_HospitalWrapperForREST(hospital));
        }
        return hospitalsWrapperForSOAP;
    }
}